apiVersion: v1
kind: Service
metadata:
  name: go-httpserver-svc
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: httpserver-pod
          image: '__IMAGE__'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
